version: '3.1'
services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USERNAME: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/data/
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - pgdata:/var/data/
  app:
    depends_on:
      - db
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/exfin
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: db:5432
      WAIT_AFTER_HOSTS: 5
      CGO_ENABLED: 0
volumes:
  pgdata:
